### ISSUE TITLE
Adding member variables to a GameObject causes runtime error when calling `createObject`

### ISSUE THREAD

**Issue by jcollard** [LearnCodeOrg/codetrain#3]
# Overview

I am trying to create member variables that can be used across objects. This works well until call `createObject` or `destroyObject`.

## How to Reproduce

Create a scene with two objects. Then press the `w` key to call `createObject`.

### Object 1:

```javascript
// called every frame
function update() {
  if (isKey('w')) createObject('player', 0, 0, 'player2');
}
```

### Object 2:
```javascript
let self; // Create a variable to be able to reference self

function start() {
  self = this; // assign self to `this`
  self._time = new Date().getTime(); // create a member variable to track the time.
}

// called every frame
function update() {
  const current = new Date().getTime();
  self._time = current; // After calling `createObject`, `self._time` will be undefined.
}
```

**Comment by csaye** [comment]
Thanks for letting me know. I believe this is happening because all object functions are regenerated whenever `createObject` or `deleteObject` is called. It makes sense to maintain existing objects through these updates, though — I'll look into a fix.

**Comment by csaye** [comment]
Should be fixed by c5213217aaaa1631bd9f4184124464c2bde7078a. I believe the issue was that new objects were not having their `start` functions run.

**Comment by jcollard** [comment]
Thanks!

Does this call `start` on all existing game objects? Or just new game objects?

**Comment by jcollard** [comment]
It seems that this error still occurs when calling `deleteObject`.

Use the above example except change `createObject` to `deleteObject`:

```javascript
// called every frame
function update() {
  if (isKey('w')) createObject('player', 0, 0, 'player2');
}
```

**Comment by csaye** [comment]
It calls `start` on new GameObjects. Let me look into the `deleteObject` issue.

**Comment by csaye** [comment]
Fixed with 97fddc167d8be4a794294a0cea4fbbd5084b8678. Objects are no longer fully regenerated every time `deleteObject` is called.
